services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    build: .
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped
    command: odoo -u icofr,icofr_demo -d odoo

volumes:
  odoo_db_data:
  odoo_web_data: